### ISSUE TITLE
Team block needs margin/passing options

### ISSUE THREAD

**Issue by jb510** [brainstormforce/ultimate-addons-for-gutenberg#1176]
### Is your feature request related to a problem? Please describe.
Using the TEAM block there are needed margin and padding controls missing.  Specifically we need to add margin around the featured image and left padding on the text fields.

Note: this is using the Ultimate Add-ons for Gutenberg Beta v2.0.0-beta.1, WP 5.9.. Theme is Astra Pro.

### Describe the solution you'd like
Same margin/padding controls in use in other elements.  

### Describe alternatives you've considered
Custom CSS...  but for something so fundamental that seems like it should be necessary.  

### Additional context/screenshots
![CleanShot 2021-12-23 at 16 51 45](https://user-images.githubusercontent.com/801241/147310319-34c58d1a-cc04-4466-9ba0-b0b7b27c427b.png)

**Comment by AbhijitNage123** [comment]
Hello @jb510,

Thanks for reaching out to us!

We do have an option for Margin for Image. See here - https://share.getcloudapp.com/2NuvKPo2

To add left padding on the text fields you can use the right margin of the image to add a space between image and text. See [here](https://share.getcloudapp.com/z8ukv19Q)

I hope you understand.

Let me know if I'm missing anything.

Regards,
Abhijit

**Comment by jb510** [comment]
TY.  It's very strange to me that is in the style sub-panel instead of immediately with where you add the image.  I kind of get the logic, just would never have found it on my own.
