### ISSUE TITLE
Team Block Bottom Spacing on Description has no effect

### ISSUE THREAD

**Issue by jb510** [brainstormforce/ultimate-addons-for-gutenberg#1177]
### Describe the bug:
When adjusting the Bottom Spacing in the Description sub-panel I would expect this to affect the vertical spacing between two team blocks. It appears to do nothing.
 
### To reproduce:
Insert 2 team blocks using the layout in the screenshot.  

Adjust bottom spacing on description.  Nothing happens.

### Screenshots:
![CleanShot 2021-12-23 at 17 03 26](https://user-images.githubusercontent.com/801241/147310949-3fcbaf9d-623f-4cb9-aea9-b5cba0dd25e1.gif)

### WordPress version:
UAG  2.0.0-beta.1
WP 5.8.2
Astra

**Comment by AbhijitNage123** [comment]
Hello @jb510,

Thanks for reaching out to us!

We have fixed that issue. It is merged in `next-release` branch.

Please see here - https://share.getcloudapp.com/eDulAgeY

Please try our latest zip from [here](https://dev.ultimategutenberg.com/wp-content/uploads/uag-gh/next-release/ultimate-addons-for-gutenberg.zip)

I hope it helps.

Let me know how it goes.

Regards
Abhijit

**Comment by jb510** [comment]
TY, but I'm already using that beta (v 2.0.0-beta.1).  I tried reinstalling it in case you all weren't actually updating version numbers, but the result was the same.  Bottom spacing had no effect.

**Comment by jb510** [comment]
Here is a video.  Looks like the Margin-bottom: 0 is coming from another element for editor styles (highlighted at end of video. https://cloudup.com/c5IpsV4eCbG

**Comment by jb510** [comment]
This may have been css another dev added to your child theme.  Sorry for wasting your time if that's the case.
