### ISSUE TITLE
Posts carousel with CPT

### ISSUE THREAD

**Issue by martinosmartinos** [brainstormforce/ultimate-addons-for-gutenberg#119]
Good day!
I am trying to display custom post types in post carousel block but it looks like UAG is not seeing registered custom post types and offers only option to choose either from normal posts, pages or media files. Am I missing something?

**Comment by martinosmartinos** [comment]
I am going to answer my own question as it might help someone facing same issue. After digging into plugin's code I discovered post carousel is fetching only objects which are 'rest' enabled so after adding 'show_in_rest' => true to my custom post type registration I can see it in a dropdown of available options. I am not sure though why custom post type should be exposed in rest API.

**Comment by vrundakansara** [comment]
Hey @martinosmartinos ,

Good day!
Yes, you are absolutely correct, `show_in_rest` should be set to `true`.
This is how it works for Gutenberg.

In case you don't want to expose your CPT to REST API, you can try working with UAG Post Filters. This filter will work on the frontend only.
You can paste the filter code in your functions.php file. The filter is as shown below.

```php
add_filter( 'uagb_post_query_args_carousel', function( $query_args, $id ) {
	$query_args['post_type'] = 'your_cpt_slug';
	return $query_args;
}, 10, 2 );
```

I hope that helps.

Regards,
Vrunda Kansara
