### ISSUE TITLE
Add option to hide front page in grid post

### ISSUE THREAD

**Issue by jp-io** [brainstormforce/ultimate-addons-for-gutenberg#120]
When using post grid on the front page to display all other pages, it would be helpful to exempt the front page from the listed pages. Couldn't find a simple work around...

**Comment by vrundakansara** [comment]
Hey @jp-io ,

Thank you for reaching us out.
You can try working with UAG Post Filters. This filter will work on the frontend.
You can paste the filter code in your functions.php file. The filter is as shown below.

```php
add_filter( 'uagb_post_query_args_grid', function( $query_args, $id ) {
	$query_args['post__not_in'] = get_the_ID();
	return $query_args;
}, 10, 2 );
```
This will exclude the current post from the query.
I hope that helps.

Regards,
Vrunda Kansara
