### ISSUE TITLE
Table of Content crashes after adding new header

### ISSUE THREAD

**Issue by tasnimAlam** [brainstormforce/ultimate-addons-for-gutenberg#123]
![table_of_content](https://user-images.githubusercontent.com/22883823/67919088-1d4b8e80-fbc9-11e9-8ba3-cf56332a0017.gif)

**Comment by vrundakansara** [comment]
Hey @tasnimAlam ,

Thank you for bringing this to us.
Are you using WordPress Beta version? This works for the stable WP version - v5.2.4
This issue is fixed for WordPress v5.3 beta. We will release an update very soon.

Regards,
Vrunda Kansara
