### ISSUE TITLE
When there's only one block in an Advanced Column the "move block" handles are missing

### ISSUE THREAD

**Issue by protorob** [brainstormforce/ultimate-addons-for-gutenberg#124]
When rearranging blocks inside Advanced Columns, if the case is that there's only one block in the column, the handles for moving the block are not displayed:

https://imgur.com/gallery/yTQ6MYd

**Comment by vrundakansara** [comment]
Hey @protorob ,

This moving feature is a Gutenberg feature. They have fixed it in v5.3. Thank you for bringing this to us.
