### ISSUE TITLE
Markup refers to incorrect stylesheets 

### ISSUE THREAD

**Issue by lonix1** [brainstormforce/ultimate-addons-for-gutenberg#133]
Every once in a while the plugin generates a new css file (in the `uag-plugins` directory), but my pages still refer to the old css files, and so don't load.

I thought it was a caching issue, but it's not. I cleared server caching and client caches.

The markup is being generated with references to the incorrect uag stylesheet.

**Comment by vrundakansara** [comment]
Thank you @lonix1 for reporting this to us. It seems that you also have added tickets with dummy email IDs. Can you raise a ticket with a valid email ID so that we can communicate? 

I can't see the issue at my end.

**Comment by lonix1** [comment]
I don't know what you mean - it's not a dummy issue 🤔 

I don't know how to go through the steps to force the error. If I discover that I will report here. Or maybe someone else will advise if they have the same problem.

**Comment by vrundakansara** [comment]
@lonix1 - That is not what I meant. Can you please raise a support request here - https://www.ultimategutenberg.com/support/

I don't see this issue at my end. I need more debugging to be done at your end. Looking forward to resolving your issue ASAP.

Regards,
Vrunda Kansara

**Comment by lonix1** [comment]
Hi please don't worry about it, I've gone in a different direction. Thanks! 😃
