### ISSUE TITLE
Timeline - Add feature to change date format and allow normal string too.

### ISSUE THREAD

**Issue by vrundakansara** [brainstormforce/ultimate-addons-for-gutenberg#143]
Allow date formats like  “c.1889” for the date, i.e. “circa 1889”, “about 1889”.

**Comment by vrundakansara** [comment]
Added date format option. This will allow such a case scenario. #148

**Comment by MikaHamalainen** [comment]
I don't see how to use string in version 1.14.6. 

If I18n is used finnish speaking people would need `M d Y` if we use `d M Y` which is closest thing we can select now, I18n will add extra 'n' (genitive) after month, which doesn't make sense in current word order.
