### ISSUE TITLE
Table of contents not working if page contains a paragraph with html attributes inside

### ISSUE THREAD

**Issue by joeljv91** [brainstormforce/ultimate-addons-for-gutenberg#155]
Hi,

I'm testing table of content on my website and I found this error. When I tested the table of content with a normal page with headings,paragraph, images etc... works fine but if I insert a shortcode that generates a resultant HTML code inside a paragraph block it shows this error:

table-of-contents.js?ver=1.14.6:115 Uncaught TypeError: $headers.forEach is not a function
    at Object._run (table-of-contents.js?ver=1.14.6:115)
    at HTMLDocument.<anonymous> (?page_id=16740&preview=true:1113)
    at i (jquery.js?ver=1.12.4-wp:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4-wp:2)
    at Function.ready (jquery.js?ver=1.12.4-wp:2)
    at HTMLDocument.J (jquery.js?ver=1.12.4-wp:2)

Json data collected on data('headers') contains an invalid JSON because quotes of html attributes are not escaped.

EDITED:

I'm using the latest version 1.14.6. On version 1.14.3 it's working fine because it's setting the headings id directly on Gutenberg editor instead of frontend new method added on 1.14.4

**Comment by vrundakansara** [comment]
This has been fixed in [v1.14.9](https://github.com/brainstormforce/ultimate-addons-for-gutenberg/releases/tag/v1.14.9). Please update to latest UAG to see this fixed.
