### ISSUE TITLE
Advanced Columns -> default padding

### ISSUE THREAD

**Issue by thomasdebruin** [brainstormforce/ultimate-addons-for-gutenberg#162]
When adding Advanced Columns, the default padding (per column) seems very high/large in the editor. The content space is very narrow. On the frontend it looks good, works as expected. Is there any option to change/fix this? Or set a default value through a hook?

**Comment by vrundakansara** [comment]
Hey @thomasdebruin ,

This default padding in the Gutenberg editor is a theme feature. Your theme needs to be Gutenberg editor compatible. I see it [like this](https://share.getcloudapp.com/JruWB55w) with [Astra](https://wordpress.org/themes/astra/) theme.

I hope this helps you.

Regards,
Vrunda Kansara
