### ISSUE TITLE
Failed to pass AMP check due to the CSS size too large

### ISSUE THREAD

**Issue by gralance** [brainstormforce/ultimate-addons-for-gutenberg#163]
The classname is too verbose, e.g.

`uagb-block-401730bd-a564-458d-85ea-313bfe1a91e3`

Looking for a short naming style:
`ub401730bd`

or does there is an option to make all CSS inline?

**Comment by vrundakansara** [comment]
@gralance - Ultimate Addons for Gutenberg does not support AMP yet. Also, a shorter class name is not possible yet.

I will try to find a solution to it. I appreciate your efforts.
