### ISSUE TITLE
Need ability to rely on theme's font-size and color for type elements

### ISSUE THREAD

**Issue by stacyk** [brainstormforce/ultimate-addons-for-gutenberg#164]
When I edit a block, for instance, post grid, I am trying to use my themes heading, link, text colors. When I try to "clear" these settings from adding inline style, it will try to use color: inherit in the editor until you publish/update and refresh. After you refresh, it automatically assigns a color that I didn't choose and declare it in the CSS with that overly specific classname which is hard to overwrite without really bad CSS.

I think this is a UAGB issue but incase it is a theme issue, this is using Astra. This first screenshot show that I used the clear button for `Title` color. It shows the theme's `Text` color set in the Customizer (even though that is a link and should use the Link Teal color). The  CSS is showing `color: inherit` which is why it uses the text color. If it didn't have any color assignment at all, then it would use the link color. 

![color-1](https://user-images.githubusercontent.com/1581694/82391585-40277e00-9a07-11ea-8d9b-ac0948926b2a.jpg)

---

![color-2](https://user-images.githubusercontent.com/1581694/82391589-43226e80-9a07-11ea-95b2-9619e5f5b059.jpg)

It would be nice to have nothing output if you clear it.

**Comment by vrundakansara** [comment]
Thank you @stacyk for bringing this to us.
I will look into it.

**Comment by vrundakansara** [comment]
@stacyk - This has been fixed here in this PR - #280 
This will be released in the upcoming update.

**Comment by vrundakansara** [comment]
This feature is released in [v1.16.0](https://wordpress.org/plugins/ultimate-addons-for-gutenberg/)
