### ISSUE TITLE
Icons on Multi-button

### ISSUE THREAD

**Issue by roadsunknown** [brainstormforce/ultimate-addons-for-gutenberg#272]
### Is your feature request related to a problem? Please describe.
Unable to add icons to the Multi Buttons block. The Info Box block, Marketing Button block and Call to Action Block all have ability to add icon to buttons in the respective block.

### Describe the solution you'd like
Port the same functionality from the Info Box block (or the Call to Action block) to _optionally_ add an icon to the Multi Buttons block.

### Describe alternatives you've considered
The Marketing Button block is an alternative but the Title is an H6 tag - hardcoded and cannot be changed. The Info Box block is also an alternative but is more complex than necessary for a simple button with an icon.

### Additional context/screenshots
None currently.

**Comment by RajkiranBagal** [comment]
Hey @roadsunknown,

Thanks for the suggestion!

I am adding this as a feature request in our task list.

It will surely be added to our future upcoming updates.

Regards,
Rajkiran
