### ISSUE TITLE
Add Marketing Button Block Title Tag Option

### ISSUE THREAD

**Issue by roadsunknown** [brainstormforce/ultimate-addons-for-gutenberg#273]
### Is your feature request related to a problem? Please describe.
The Title in the Marketing button block is hard-coded as a H6 and cannot be changed.

### Describe the solution you'd like
Add option to set the Title Tag similar to that the Price List block which allows selection of Title Tag (H1-6, P, SPAN).

### Describe alternatives you've considered
None.

### Additional context/screenshots
None currently.

**Comment by RajkiranBagal** [comment]
Hey @roadsunknown,

Thanks for the suggestion!

I am adding this as a feature request in our task list.

It will surely be added to our future upcoming updates.

Regards,
Rajkiran
