### ISSUE TITLE
Call To Action anchor does not save

### ISSUE THREAD

**Issue by roadsunknown** [brainstormforce/ultimate-addons-for-gutenberg#297]
### Describe the bug:
The Call To Action block property "HTML Anchor" does not save. If you enter text as per instructions and update (save) post/page, everything seems correct. However, if you visit the page/post, the HTML Anchor tag (id=) is not rendered. If you refresh the editor, the HTML Anchor no longer exists.

### To reproduce:

1. Go to Pages or Posts
2. Create a Page/Post or Edit any Page/Post
3. Insert "Call to Action" block.
4. Scroll to Advanced section in Block settings.
5. Enter a word or two — without spaces.
6. Click Update.

### Expected behavior:
Expect HTML Anchor tag to be added to Call to Action block parent div.

### Screenshots:
![image](https://user-images.githubusercontent.com/371759/84560745-5e358500-ad0c-11ea-8de9-3f8b90b9f55d.png)

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active
- [X] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4.2

### Gutenberg version:
General Release

**Comment by RajkiranBagal** [comment]
Hey @roadsunknown,

Thank you for reporting this issue.

I have added a task for this issue to be fixed and it will be fixed in our upcoming updates.

Your patience and co-operation are highly appreciated.

Regards,
Rajkiran.

**Comment by roadsunknown** [comment]
@RajkiranBagal Any updates? Does not appear this made it into the latest release 1.16.1: https://www.ultimategutenberg.com/changelog/.

**Comment by RajkiranBagal** [comment]
Hey @roadsunknown,

We have fixed this issue and it is in the testing phase.

It will surely be released in our upcoming update.

If you want a development version of this fix then, Please open a ticket [here](https://www.ultimategutenberg.com/support/open-a-ticket/), So that we can provide you with the same.

Looking forward to hearing from you.

Regards,
Rajkiran.

**Comment by RajkiranBagal** [comment]
Hey @roadsunknown,

Closing this issue as we received no response from you for a long time.

Regards,
Rajkiran
