### ISSUE TITLE
Can a Table of content be a element of a FSE template ?

### ISSUE THREAD

**Issue by DSGND** [brainstormforce/ultimate-addons-for-gutenberg#3267]
### Describe the bug:
- Front office : The TOC returns "Add a header to begin generating the table of contents" whereas the post has many Hx titles.

### To reproduce:
- Back office : I'm creating a two column post template with WordPress Site Editor (FSE)
   - The left column has the Spectra Table of content
   - The right column has the content of the post

### Expected behavior:
The TOC must display all Hx titles and link to them

### Screenshots:
Custom theme + plugins
![image](https://github.com/brainstormforce/ultimate-addons-for-gutenberg/assets/13942136/bb5c8da7-b835-467e-8c5e-d2c3cb6841b7)

TwentyTwentyThree theme + no plugin
![image](https://github.com/brainstormforce/ultimate-addons-for-gutenberg/assets/13942136/0e047d44-696f-47f2-89cc-76a101a16bd0)

### Isolating the problem:

- [X] This bug happens with no other plugins activated
- [X] This bug happens with a default WordPress theme active
- [X] This bug happens **without** the Gutenberg plugin active
- [X] I can reproduce this bug consistently using the steps above

### WordPress version:
6.2.2

### Gutenberg version:
14.2-15.1 (which is included in WP 6.2 : https://developer.wordpress.org/block-editor/contributors/versions-in-wordpress/)

**Comment by AbhijitNage123** [comment]
Hello @DSGND,

Thank you for reporting this issue to us!

We are pleased to inform you that we are aware of this issue, and our development team has already created a pull request (PR) to address it. You can find the PR at this link: [PR](https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/3239).

For further reference, we have also prepared a screencast demonstrating our testing process. You can view it here: [Screencast](https://share.getcloudapp.com/z8ubwgxQ).

Thank you for bringing this to our attention, and we appreciate your patience as we work towards resolving the issue. Let us know if you have any further questions or concerns.

Best regards,
Abhijit
Spectra Development Team

**Comment by DSGND** [comment]
Hi @AbhijitNage123 !
Thank you for your response.
Hope the fix will be released very soon! Do you have an idea about when it will?

**Comment by DSGND** [comment]
Hi @AbhijitNage123!
Any news for the fix?

**Comment by DSGND** [comment]
TOC can be used in FSE patterns or templates in Spectra 2.7.10 (maybe before…)

We can close this ticket.
