### ISSUE TITLE
Spectra Container full width is not full width

### ISSUE THREAD

**Issue by RichardJECooke** [brainstormforce/ultimate-addons-for-gutenberg#3309]
### Describe the bug:
The Wordpress Row, when set to full width, will display from the left to the right edge of the browser.  But you can't give it a background image.

The Spectra Container can be given a background image. But if you set it to full width it doesn't run from the left to the right edge of the browser. And if you put the Container inside a Wordpress Row it doesn't fill the row.

### To reproduce:
1. Add a Spectra Container to a page.
2. Set its background image in the Style tab to an image as wide as your screen, like a wallpaper.
3. Set its container width to Full Width, or Custom 100% or 100VW, in the General tab.
4. Save and view the page. See there's a gap on either side of the container.

### Expected behavior:
There is no gap on either site of the container

### Screenshots:
![spectra_container](https://github.com/brainstormforce/ultimate-addons-for-gutenberg/assets/5468805/e236ed94-84d4-4d51-bdd3-f93ccc438877)

### Isolating the problem:

- [x ] This bug happens with no other plugins activated
- [ x] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active - don't know what this means
- [ x] I can reproduce this bug consistently using the steps above

### WordPress version:
6.2.2

### Gutenberg version:
don't know

**Comment by AbhijitNage123** [comment]
Hello @RichardJECooke,

Thank you for reporting this issue to us!

It appears that the default global padding added from the theme editor is causing the left and right gaps in the layout. As a result, the Spectra Container does not span from the left to the right edge of the browser when set to full width.

To resolve this issue, you can adjust the global padding settings in the theme editor. By reducing or removing the padding on the left and right sides, you should be able to achieve the desired effect of the Spectra Container filling the entire row.

Here's a visual representation of the issue and the suggested solution: [screencast link](https://share.getcloudapp.com/12ukKn81)

I hope this helps to address the problem. 

Best regards,
Abhijit
Spectra Development Team

**Comment by RichardJECooke** [comment]
Thank you! I thought if the padding was empty (and the slider is all the way to the left) it means 0.  That is a very confusing design by Wordpress. I actually think I should log a usability issue with them. I'll reference your screencast.
