### ISSUE TITLE
Greedy CSS selector affecting all of Gutenberg, bind only to your plugin please

### ISSUE THREAD

**Issue by dovy** [brainstormforce/ultimate-addons-for-gutenberg#331]
### Describe the bug:
Inside ~/dist/blocks.style.css?ver=1.16 is the following line: `.uagb-ifb-left-right-wrap, button.components-button {z-index:1;}`. This affects all of Gutenberg causing the components-tooltip to go behind all components-buttons.

### To reproduce:
Use your plugin.

### Expected behavior:
Bind those styles on to your own components as not to affect gutenberg as a whole.

### Screenshot
https://cldup.com/11F5jZgxFN.png

### Isolating the problem:

- [x ] This bug happens with no other plugins activated
- [x ] This bug happens with a default WordPress theme active
- [x ] This bug happens **without** the Gutenberg plugin active
- [x ] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4.2

**Comment by vrundakansara** [comment]
Hey @dovy ,

Thank you for reporting this to us. We will get it fixed in the upcoming update.

Regards,
Vrunda Kansara

**Comment by dovy** [comment]
Excellent. Would you like me to close this or will you when the release happens?

**Comment by vrundakansara** [comment]
@dovy - We have fixed it here and very soon we will release an update. #334 
I will close this issue since the PR is merged.

**Comment by dovy** [comment]
Thank you.
