### ISSUE TITLE
Full-width for Twenty-Twenty-Template

### ISSUE THREAD

**Issue by errotu** [brainstormforce/ultimate-addons-for-gutenberg#350]
First, thanks a lot for your great work and this fantastic plugin!

### Is your feature request related to a problem? Please describe.
There is no full-width option using UAG with the Twenty Twenty wordpress theme (while the theme generally supports fullwidth blocks).

### Describe the solution you'd like
I should be able to display UAG-blocks in full-width mode using the current wordpress standard template Twenty Twenty.

Are there any plans to implement such feature? Or am I missing something and displaying block full-width should work in Twenty Twenty?

**Comment by AbhijitNage123** [comment]
Hello @errotu 

I am glad you liked our plugin.

Thanks for your suggestion.

The full width and wide width classes, alignfull , alignwide are added to respective blocks on the selection of the full-width options. These classes have their properties defined in the active theme. These properties will act differently in different themes. Twenty Twenty theme has its own definition of these classes. WordPress core Cover block and UAG Advanced Columns full-width option will have the same width in this theme.

Your patience and co-operation are highly appreciated.

Regards,
Abhijit.

**Comment by RajkiranBagal** [comment]
Hey @errotu,

Due to no response for a long time from you, we are closing this Issue.

Please let us know if you face any more issues, we are always there for you.

Have a Great Day ahead!
