### ISSUE TITLE
Icon List Font Size rendered as PX when configured as EM

### ISSUE THREAD

**Issue by roadsunknown** [brainstormforce/ultimate-addons-for-gutenberg#352]
### Describe the bug:
When the typography font-size is configured as "em", there are two styles rendered, one is correctly "em" but another is "px". This renders the "em" useless and the text too small.

### To reproduce:

1. Insert a Icon List block
2. Adjust Typography > Font Size to 1.2
3. Configure the measurement to "em"
4. Publish and view source

### Expected behavior:
The font-size property should be set to 1.2em but is instead set to 1.2px on `.uagb-icon-list-repeater`. Also, unsure if necessary to render styles twice (2x), both on `.uagb-icon-list-repeater .uagb-icon-list__label` and `.uagb-icon-list-repeater`. One solution may be to remove the rendering of any styles on `.uagb-icon-list-repeater`.

Related issue, if line-height is not also set, an empty line-height style is rendered (and is marked invalid). Un-configured styles should never be rendered.

### Screenshots:
![image](https://user-images.githubusercontent.com/371759/89230250-8de46900-d5a8-11ea-8a77-5bfb32eacf3e.png)

### Isolating the problem:

- [?] This bug happens with no other plugins activated
- [?] This bug happens with a default WordPress theme active
- [X] This bug happens **without** the Gutenberg plugin active
- [X] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4.2

**Comment by AbhijitNage123** [comment]
Hey @roadsunknown,

Thank you for reporting this issue.

I have added a task for this issue to be fixed and it will be fixed in our upcoming updates.

Your patience and co-operation are highly appreciated.

Regards,
Abhijit

**Comment by RajkiranBagal** [comment]
Hey @roadsunknown ,

I am closing this issue as we have Fixed this issue & released it in version 1.17.0.

Please let us know if you face any issues, we are always there for you.

Regards,
Rajkiran.
