### ISSUE TITLE
Post Carousel glich with Astra Theme (from version 1.20)

### ISSUE THREAD

**Issue by carloreggiani** [brainstormforce/ultimate-addons-for-gutenberg#483]
Hi

With the last version in the Post Carousel block the dimension of the images is not managed as well, specially with the autoloop mode.

In edit mode it seems all ok, after publishing the page the block seems have no correct dimension to contain the images and title and excerpt, both on desktop and mobile mode.

Any fix?

Thanks

Carlo

**Comment by AbhijitNage123** [comment]
Hey @carloreggiani,

Thanks for reaching out to us.

We have already released a patch for all issues related to the Post  Carousel block in our V1.20.1.

Could you please share any screenshots or videos where I can check what issue you are facing?

Looking forward to resolving your issue.

**Comment by carloreggiani** [comment]
Hi @AbhijitNage123 sorry for delay: the v1.20.1 resolved the but, now the Post Carousel block works fine!

Thank you

Carlo

**Comment by RajkiranBagal** [comment]
We are glad to header your issue is resolved @carloreggiani!

Have a Great Day ahead!
