### ISSUE TITLE
Conditionally load the images for the UAG templates; they're being loaded every time the editor is open

### ISSUE THREAD

**Issue by skorasaurus** [brainstormforce/ultimate-addons-for-gutenberg#517]
### Describe the bug:

The UAG templates are automatically loaded when the plugin is active and the editor is open and that adds considerable overhead; automatically loads over a dozen images, which is several hundred KB. 

### To reproduce:

1. Install, activate plugin
2. go to yoursite.com/wp-admin/post-new.php?post_type=page
3. control + c + shift (in firefox), go to network tab
4. view the resources that are being used.

### Expected behavior:
the images would only be loaded if the user open the UAG templates

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active
- [ ] I can reproduce this bug consistently using the steps above

### WordPress version:
WP 5.7

### Gutenberg version:
gutenberg 10.

**Comment by vrundakansara** [comment]
Hello @skorasaurus ,

Thank you for reporting this to us.
I have added this as a feedback task and our team will start working on it. Probably in the upcoming few updates, we will handle this.

**Comment by skorasaurus** [comment]
Hi, 

I read this has been implemented in the newest update and verified it works as expected; thank you 

https://ultimategutenberg.com/docs/remove-uag-templates-button/
