### ISSUE TITLE
📣 Ultimate Addons for Gutenberg v1.23.0 Beta 1 Release 📣

### ISSUE THREAD

**Issue by sandeshjangam** [brainstormforce/ultimate-addons-for-gutenberg#717]
# v1.23.0 Beta 1

Hello, UAG Beta testers 👋

We are here with the Ultimate Addons for Gutenberg (UAG) v1.23.0 Beta.

This version of UAG brings impressive speed improvements that will make your websites load faster than ever before. It also brings new useful features like an option to rollback to the previous version & beta version updates directly in the dashboard.

We invite you to try out UAG v1.23.0 Beta. We would love to hear how you like this update and your suggestions that will help to improve this UAG version. 

We strongly recommend using the beta version in a test environment and not on a live site. This way, you can try out the beta version without worrying about anything going wrong on the live site.

Let’s check what's in this update - 

![image5](https://user-images.githubusercontent.com/15683894/120320516-e509b600-c2ff-11eb-858f-66b45925ec6e.png)

# Improved Assets (CSS/JS) Loading for Faster Gutenberg Pages

UAG version 1.23.0 focuses on speed improvement and performance optimization. This ensures that when you use any UAG block on your website, it will load with the minimum page requests and the minimum page size, giving you the fastest loading time.

This version brings more optimized CSS and JS code.

The previous UAG version was used to load a static CSS file of size **164KB**. 

Now, in the improved logic, UAG will conditionally load this CSS file based on the blocks used on the page. This eliminates the request to load static CSS, which brings significant improvement in the performance.  Your page will now need **1 Less HTTP request.**

UAG will also cache the generated assets in the respective post's meta & files. Later, a plugin will serve these cached dynamic assets on the page instead of generating the assets on page reload. This improvement in the logic will reduce the page load time.

# Improved Table of Contents Rendering Logic to Reduce CLS Impact

Previously, UAG used to load the TOC headings markup through JavaScript on page load, causing the page's CLS issue.

Now, the markup will load through PHP itself. This will prevent generating CLS issues. 

# New Option: Regenerate Assets

![image](https://user-images.githubusercontent.com/15683894/120315086-96f1b400-c2f9-11eb-8c8d-68b9584c36b9.png)

After switching to the latest UAG version, if the colors or design are not showing up as it was initially in the frontend, you can use this option. This will quickly regenerate the CSS and JS files required for the page. This option could fix any design or layout-related issues on your UAG pages.

This option will be available on the UAG settings page under **Settings > UAG**. 

# New Option: Rollback to Previous Version

![image3](https://user-images.githubusercontent.com/15683894/120318787-e3d78980-c2fd-11eb-931a-7bb912376c25.png)

This is another small but helpful control. It will allow you to switch to previous versions of UAG with just a click. After updating UAG to the latest version, if you experience any issue, you can quickly roll back to the previous version.

This option will be available under **Settings > UAG > Tools**. 

# New Option: Enable Beta Updates

![image4](https://user-images.githubusercontent.com/15683894/120318819-ee921e80-c2fd-11eb-8dd9-20de505aa73d.png)

While releasing any major UAG version, we follow a beta testing process. It helps us to provide a working copy of the upcoming release with you and get feedback on the new features, improvements, and fixes.

Now you can easily participate in the beta testing process with this new option. Just visit the **Settings > UAG > Tools**  and click on the ‘Enable Beta Updates’ button. This will fetch the latest beta version and will show the notification in your dashboard.

# Full changelog

* New: Added an option to rollback to a previous version.
* New: Added an option to get update notifications for beta versions.
* New: Lottie - Added alignment Option.
* Improvement: Frontend optimization by reducing one request of CSS.
* Improvement: Improved the Dynamic Assets loading functionality for better performance.
* Improvement: Static CSS Optimized by loading only used blocks' CSS on a Page.
* Improvement: Table of content - Optimized headings rendering to remove CLS impact.
* Fix: Advanced Column - Column Gap Setting overlapping issue.
* Fix: Advanced Column - Column Gap Setting not working in the Editor issue.
* Fix: Advanced Column - Stack on tablet and mobile in preview mode.
* Fix: Blockquote - Tweet link showing an empty page link and username.
* Fix: Block condition - Conflicting with Real Media Library plugin.
* Fix: Blocks throwing an error when deactivated all the UAG blocks except the Multi Buttons, Forms & How To.
* Fix: Inline Notice and Review Schema block UI broken if Gutenberg plugin is activated.
* Fix: Lottie - Settings conflict issue.
* Fix: Lottie - Alignment issue in the editor.
* Fix: Post Grid - Link to complete box redirect to the last post when image background set to Top.
* Fix: Post Layout - Conflicting with the Envira Gallery plugin.
* Fix: Post Layout - Invalid HTML markup of a post meta link.
* Fix: Section - Margin Left/Right not working issue.
* Fix: Social Share - Query string variables were omitted after the first ampersand. Encoded the Page/Post URL.
* Fix: Table of content - HTML validation issue.

# How to Install the Beta Version?

You can download the new version here: [ultimate-addons-for-gutenberg-1.23.0-beta1.zip](https://github.com/brainstormforce/ultimate-addons-for-gutenberg/files/6598327/ultimate-addons-for-gutenberg-1.23.0-beta1.zip)

# How to Report a Bug?

If you think you’ve found a bug, please reply with a comment on this issue here on GitHub.

**Please keep this related to the current beta only! For any other issue or feature request, feel free to open a new issue.**

Thanks for your support and help...!

<hr>

**`Tentative release date: June 8, 2021`**

<hr>

Cheers,
Ultimate Addons for Gutenberg Team

**Comment by vrundakansara** [comment]
Wow! Congratulations team! 🎉

**Comment by monika-12** [comment]
Awesome !! Good work team 👏
