### ISSUE TITLE
Adding custom CSS to the REST-API

### ISSUE THREAD

**Issue by reinoldus** [brainstormforce/ultimate-addons-for-gutenberg#76]
Hello,
I am using wordpress as a headless CMS. This issue is that UAGB renders custom css on the post-page, which is not included in the WP-REST-API call.

Would it be possible to add this as well?

**Comment by vrundakansara** [comment]
Hey @reinoldus ,

WordPress saves the blocks in the form of a parsed data into the post_content field for the posts.

The parsed content is not directly accessible in API. The unparsed text is accessible on index `content.rendered`. One needs to add the original content using REST API functions.

The below function should help you. Add the code in your functions.php file.

```php
register_rest_field(
	'page',
	'block_content',
	array(
		'get_callback' => function ( $object = '', $field_name = '', $request = array() ) {
			return get_post_field( 'post_content', $object['id'] );
		},
		'schema'       => null,
	)
);
```
This will add the original content on index `block_content` for API.
Also, the CSS generated now is loaded in the head. In the upcoming milestone, we have the CSS loaded as per the pages from dynamic files. This issue will be resolved then.

I hope this helps.

Regards,
Vrunda Kansara
