### ISSUE TITLE
Radio Button's not working in forms

### ISSUE THREAD

**Issue by rutviksavsani** [brainstormforce/ultimate-addons-for-gutenberg#805]
### Describe the bug:
The Form does not show the radio buttons when it goes live. 

### To reproduce:
1. Add a form to a Post in WordPress Editor.
2. Add a Radio item to form 
3. Publish the form and you will find it does not have option to select radio option.

### Expected behavior:
- Should be able to select a radio option
- Should be Visible

### Screenshots:
![Screenshot from 2021-07-13 14-19-01](https://user-images.githubusercontent.com/53530700/125422820-b11d2e90-4af0-4be9-a060-d9104488852e.png)

### Isolating the problem:

- [ X ] This bug happens with no other plugins activated
- [ X ] This bug happens with a default WordPress theme active
- [ X ] This bug happens **without** the Gutenberg plugin active
- [ X ] I can reproduce this bug consistently using the steps above

### WordPress version:
WordPress 5.7.2 running Twenty Twenty-One theme.

### Gutenberg version:
Version 11.0.0

**Comment by supriyajjadhav** [comment]
Hi rutviksavsani,

Thanks for reaching out to us.

I'm able to replicate the same at our end.

I have added a task to our to-do list and assign it to the concerned developer to debug this further. It will be fixed in our upcoming updates.

Till then your patience is highly appreciated.

**Comment by rutviksavsani** [comment]
sure, waiting for the update cheers!!

**Comment by supriyajjadhav** [comment]
Hello rutviksavsani,

We are thankful for your patience and readiness to help us fix things that we come across. I'd like to let you know, we have fixed this issue in our version 1.23.5. I'd request you to please update the plugin to the latest version to fix your problem. 

Let me know how it goes.

**Comment by rutviksavsani** [comment]
fixed
