### ISSUE TITLE
Notice displaying Social Share block

### ISSUE THREAD

**Issue by bobbingwide** [brainstormforce/ultimate-addons-for-gutenberg#88]
Problem occurs because no background colour has been defined for the icons.

```
Notice: Undefined index: icon_bg_hover_color in /home/bworguk/public_html/wp-content/plugins/ultimate-addons-for-gutenberg/classes/class-uagb-block-helper.php on line 1742
```

See https://blocks.wp-a2z.org/block/social-share-uagb-social-share/

I raised this as a support ticket just a few moments ago. Then I matched bsf.io to brainstormforce, put two and two together and answered part of the ticket myself. 

Note: Problem no longer occurs on the above URL as I have applied the fix below.

**Comment by bobbingwide** [comment]
Adding a couple of lines to `classes/class-uagb-block-helper.php` resolves the issue. Around line 1705
```
$social['icon_color'] = ( isset( $social['icon_color'] ) ) ? $social['icon_color'] : '';
$social['icon_bg_color'] = ( isset( $social['icon_bg_color'] ) ) ? $social['icon_bg_color'] : '';
$social['icon_hover_color'] = ( isset( $social['icon_hover_color'] ) ) ? $social['icon_hover_color'] : '';
$social['icon_bg_hover_color'] = ( isset( $social['icon_bg_hover_color'] ) ) ? $social['icon_bg_hover_color'] : '';
```

**Comment by bobbingwide** [comment]
I've created PR #89

**Comment by vrundakansara** [comment]
This has been merged and will be released in the upcoming version.
