### ISSUE TITLE
Cannot Enter Decimal Values for Font Sizes in EM

### ISSUE THREAD

**Issue by roadsunknown** [brainstormforce/ultimate-addons-for-gutenberg#96]
**Steps to Reproduce:**
1. Add Advanced Heading block to Page
2. Go to Advanced Heading > Heading > Typography > Font Size
3. Select em (px is default)
4. Enter decimal value, e.g. 3.5

_Actual Result:_ 
1. Displays tooltip, e.g. "Please enter a valid value. The two nearest values are 3 and 4."
2. Auto adjusts value to lower value, e.g. 3.

_Expected Result:_ 
When em is selected, decimal values should be valid and not corrected.

Version: 1.13.6

Applies to all instances of Typography > Font Size setting in Ultimate Add-ons for Gutenberg blocks.

May be similar to Line Height decimal issue resolved in 1.13.3.

**Comment by vrundakansara** [comment]
Hey @roadsunknown 

Thank you for reporting this. We have fixed this #100
