### ISSUE TITLE
Post Grid - Read More Link No Button Hover

### ISSUE THREAD

**Issue by roadsunknown** [brainstormforce/ultimate-addons-for-gutenberg#97]
When the Read More Link is enabled on Post Grid block, the hover button border style is not applied.

**Steps to Reproduce:**
1. Add Post Grid Block to page
2. Enable Read More Link
3. Configure Button Border, e.g. Solid, 2px
4. Configure Button Colors > Normal and Hover (select two different contrasting colors)

_Actual Result:_
Hover border styles are not rendered, output same as Normal border.

_Expected Result:_
Hover border styles are rendered per configuration.

**Comment by vrundakansara** [comment]
Hey @roadsunknown ,

This is been fixed and will be released very soon - #101
