### ISSUE TITLE
Post Grid - Read More Link Invalid Font Family: Default

### ISSUE THREAD

**Issue by roadsunknown** [brainstormforce/ultimate-addons-for-gutenberg#98]
**Steps to Reproduce:**
1. Add Post Grid Block to page
2. Configure Read More Link
3. Confirm Typography > Font Family is set to Default

_Actual Result:_
Style renders `font-family: Default` which is invalid CSS.

`#uagb-post__grid-{guid} .uagb-post__text .uagb-post__cta a {`
~~`font-family: Default;`~~
`}`

_Expected Result:_
No font-family style is rendered, thereby inheriting default (global) style.

_Bonus Result:_
Inherit button styles from theme, e.g. Astra Theme > Customizer > Global > Buttons.

**Comment by vrundakansara** [comment]
Hey @roadsunknown ,
Thank you for reporting this to us.
This is been fixed here - #102
